# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Notes
email: casey.hume@nist.gov
description: > # this means to ignore newlines until "baseurl:"
  This is a set of notes and other practice excercises to test GitHub pages
  functionality together with other web architectures, such as materialize 
  or Sass.  
baseurl: "/notes" # the subpath of your site, e.g. /blog
# url: "http://crhume.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  crhume

# Build settings
markdown: kramdown

